### ISSUE TITLE
Address validation API not working - Fedex::RateError: Authentication Failed

### ISSUE THREAD

**Issue by spaghetticode** [jazminschroeder/fedex#96]
Hi, sorry to bother you with this issue, but I am new to the Fedex world and I was requested to use this API for address validation. 

I followed the examples, and while I can succesfully use other APIs (i.e. the rate API) the address validation doesn't work, it returns a ```Fedex::RateError: Authentication Failed``` error. Since credentials are the same I'm a bit frowned. 
Any help would be appreciated ;-)

Andrea

**Comment by jazminschroeder** [comment]
Address validation is not available in test mode so you need to use production credentials. If the problem is happening in Production then most likely the Address validation service has not been enabled for your Fedex account(you need to call Fedex and/or open a ticket so they enable the service for you)

Hope this helps!
